-- your code here
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("hooooplah", "genisis", 200000, "Nov", "Jan");


INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);
INSERT INTO users(name, age) VALUES ("bahhny", 60);

INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (25, 3, 5);
